FROM fedora-development-base

USER 0
env USER=root
WORKDIR /tmp

RUN wget "https://github.com/helix-editor/helix/releases/download/23.10/helix-23.10-$(uname -m)-linux.tar.xz" -O /tmp/hx.tar.xz \
  && tar xf /tmp/hx.tar.xz && cp /tmp/helix*/* /usr/bin/ -r \
  && rm -r /tmp/hx.tar.xz /tmp/helix*

USER 1000
ENV USER=coder
WORKDIR /home/coder

ENTRYPOINT ["zsh"]
