FROM fedora-development-base

USER 0
env USER=root
WORKDIR /tmp

ARG CODE_SERVER_VERSION=4.107.0
RUN ARCH="$(uname -m | sed 's/x86_64/amd64/g' | sed 's/aarch64/arm64/g')" \
  && wget "https://github.com/coder/code-server/releases/download/v${CODE_SERVER_VERSION}/code-server-${CODE_SERVER_VERSION}-$ARCH.rpm" -O /tmp/code-server.rpm \
  && wget https://raw.githubusercontent.com/coder/code-server/v${CODE_SERVER_VERSION}/ci/release-image/entrypoint.sh -O /usr/bin/entrypoint.sh && chmod +x /usr/bin/entrypoint.sh \
  && rpm -i /tmp/code-server.rpm \
  && rm /tmp/code-server.rpm

# Allow users to have scripts run on container startup to prepare workspace.
# https://github.com/coder/code-server/issues/5177
ENV ENTRYPOINTD=${HOME}/entrypoint.d

USER 1000
ENV USER=coder
WORKDIR /home/coder

EXPOSE 8088
ENTRYPOINT ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8088", "."]
