ARG CODE_EDITOR=helix
FROM fedora-${CODE_EDITOR}

USER 0
env USER=root
WORKDIR /tmp

RUN dnf update -y \
    && dnf install -y \
    clang \
    clang-tools-extra \
    lldb \
    fio \
    ccache \
    jq \
    iproute \
    hostname \
    gnutls-devel \
    hwloc-devel \
    ragel \
    lksctp-tools-devel \
    libasan libubsan liblsan libtsan libasan-static libubsan-static liblsan-static libtsan-static \
    python3-scipy python3-cherrypy python3-bcrypt python3-routes fuse3 \
    && dnf builddep -y ceph \
    && rm -rf /var/cache/dnf /var/cache/libdnf5

USER 1000
ENV USER=coder
WORKDIR /home/coder

ARG CODE_EDITOR
RUN if [ "$CODE_EDITOR" = "code-server" ] ; \
  then code-server --install-extension llvm-vs-code-extensions.vscode-clangd \
  && code-server --install-extension vadimcn.vscode-lldb \
  && code-server --install-extension xaver.clang-format ; fi
